# syntax
# [module.{{call_name}}]
# path = "path to install module"
# desc = "desc for module"
#

[modules.test]
path = "github.com/ihatiko/go-chef-sandbox-test"
desc = "тестовый компонент"
deprecated = true